import {build} from 'esbuild';
import {readFile, writeFile} from 'node:fs/promises';
import path from 'node:path';
const root = path.resolve(import.meta.dirname, '../..');
// The upstream package targets bundlers; bundle in memory to resolve its ESM imports.
const built = await build({stdin:{contents:"export * from '@material/material-color-utilities';",resolveDir:root},bundle:true,write:false,platform:'node',format:'esm'});
const {Hct,SchemeTonalSpot,MaterialDynamicColors,argbFromHex,hexFromArgb} = await import(`data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`);
const palettes = {garden:'#537d45',lavender:'#6750a4',ocean:'#006a6a',rose:'#984061'};
const roles = ['primary','onPrimary','primaryContainer','onPrimaryContainer','secondary','onSecondary','secondaryContainer','onSecondaryContainer','tertiary','tertiaryContainer','onTertiaryContainer','surface','surfaceContainerLowest','surfaceContainerLow','surfaceContainer','surfaceContainerHigh','surfaceContainerHighest','onSurface','onSurfaceVariant','outline','outlineVariant','error','errorContainer','onErrorContainer','inverseSurface','inverseOnSurface'];
const colors = new MaterialDynamicColors();
let css = '/* Generated by npm run launcher:themes using Google Material color utilities. */\n';
for (const [name,seed] of Object.entries(palettes)) {
  for (const dark of [true,false]) {
    const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(seed)),dark,0);
    const mode = dark ? 'dark' : 'light';
    css += `${name==='garden'&&dark?':root,\n':''}:root[data-palette="${name}"][data-mode="${mode}"] {\n  color-scheme: ${mode};\n`;
    for (const role of roles) css += `  --md-${role.replace(/[A-Z]/g,letter=>'-'+letter.toLowerCase())}: ${hexFromArgb(colors[role]().getArgb(scheme))};\n`;
    css += '}\n';
  }
}
const output=path.join(root,'public/launcher/Themes.css');
if(process.argv.includes('--check')) {
  if(await readFile(output,'utf8')!==css) throw new Error('Material palettes are stale. Run npm run launcher:themes.');
} else await writeFile(output,css);
